package lib.RequestFactory.OutputDataFront;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;

public class OutputDataFront {
    private static final List<Countries> countries = new LinkedList<>();
    private static final List<String> categories = new LinkedList<>();
    private static final LinkedHashMap<String,String> countryMap = new LinkedHashMap<String,String>();
    public static List<Countries> getCountries(){
        countries.add(new Countries("Argentina","AR"));
        countries.add(new Countries("Australia","AU"));
        countries.add(new Countries("Austria","AT"));
        countries.add(new Countries("Belgium","BE"));
        countries.add(new Countries("Brazil","BR"));
        countries.add(new Countries("Bulgaria","BG"));
        countries.add(new Countries("Canada","CA"));
        countries.add(new Countries("China","CN"));
        countries.add(new Countries("Colombia","CO"));
        countries.add(new Countries("Cuba","CU"));
        countries.add(new Countries("Czechia","CZ"));
        countries.add(new Countries("Egypt","EG"));
        countries.add(new Countries("France","FR"));
        countries.add(new Countries("Germany","DE"));
        countries.add(new Countries("Greece","GR"));
        countries.add(new Countries("Hong Kong","HK"));
        countries.add(new Countries("Hungary","HU"));
        countries.add(new Countries("India","IN"));
        countries.add(new Countries("Indonesia","ID"));
        countries.add(new Countries("Ireland","IE"));
        countries.add(new Countries("Israel","IL"));
        countries.add(new Countries("Italy","IT"));
        countries.add(new Countries("Japan","JP"));
        countries.add(new Countries("Korea (Republic of)","KR"));
        countries.add(new Countries("Latvia","LV"));
        countries.add(new Countries("Lithuania","LT"));
        countries.add(new Countries("Malaysia","MY"));
        countries.add(new Countries("Mexico","MX"));
        countries.add(new Countries("Morocco","MA"));
        countries.add(new Countries("Netherlands","NL"));
        countries.add(new Countries("New Zealand","NZ"));
        countries.add(new Countries("Nigeria","NG"));
        countries.add(new Countries("Norway","NO"));
        countries.add(new Countries("Philippines","PH"));
        countries.add(new Countries("Poland","PL"));
        countries.add(new Countries("Portugal","PT"));
        countries.add(new Countries("Romania","RO"));
        countries.add(new Countries("Russian Federation","RU"));
        countries.add(new Countries("Saudi Arabia","SA"));
        countries.add(new Countries("Serbia","RS"));
        countries.add(new Countries("Singapore","SG"));
        countries.add(new Countries("Slovakia","SK"));
        countries.add(new Countries("Slovenia","SI"));
        countries.add(new Countries("South Africa","ZA"));
        countries.add(new Countries("Sweden","SE"));
        countries.add(new Countries("Switzerland","CH"));
        countries.add(new Countries("Taiwan, Province of China[a]","TW"));
        countries.add(new Countries("Thailand","TH"));
        countries.add(new Countries("Turkey","TR"));
        countries.add(new Countries("Ukraine","UA"));
        countries.add(new Countries("United Arab Emirates","AE"));
        countries.add(new Countries("United Kingdom of Great Britain and Northern Ireland","GB"));
        countries.add(new Countries("United States of America","US"));
        countries.add(new Countries("Venezuela (Bolivarian Republic of)","VE"));
        return countries;
    }

    public static List<String> getCategories(){
        categories.add("business");
        categories.add("entertainment");
        categories.add("health");
        categories.add("science");
        categories.add("technology");
        categories.add("sports");
        categories.add("general");
        return categories;
    }

    public static LinkedHashMap<String,String> getCountriesAndCode(){

        countryMap.put("portugalia","pt");
        countryMap.put("portugal","pt");
        countryMap.put("zjednoczoneemiratyarabskie","ae");
        countryMap.put("unitedarabemirates","ae");
        countryMap.put("argentyna","ar");
        countryMap.put("argentina","ar");
        countryMap.put("austria","at");
        countryMap.put("austria","at");
        countryMap.put("australia","au");
        countryMap.put("australia","au");
        countryMap.put("rumunia","ro");
        countryMap.put("romania","ro");
        countryMap.put("serbia","rs");
        countryMap.put("serbia","rs");
        countryMap.put("belgia","be");
        countryMap.put("belgium","be");
        countryMap.put("rosja","ru");
        countryMap.put("russian","ru");
        countryMap.put("bulgaria","bg");
        countryMap.put("bulgaria","bg");
        countryMap.put("arabiaaaudyjska","sa");
        countryMap.put("saudiarabia","sa");
        countryMap.put("brazylia","br");
        countryMap.put("brazil","br");
        countryMap.put("szwecja","se");
        countryMap.put("sweden","se");
        countryMap.put("singapur","sg");
        countryMap.put("singapore","sg");
        countryMap.put("slowenia","si");
        countryMap.put("slovenia","si");
        countryMap.put("slowacja","sk");
        countryMap.put("slovakia","sk");
        countryMap.put("kanada","ca");
        countryMap.put("canada","ca");
        countryMap.put("szwajcaria","ch");
        countryMap.put("switzerland","ch");
        countryMap.put("chiny","cn");
        countryMap.put("china","cn");
        countryMap.put("kolumbia","co");
        countryMap.put("colombia","co");
        countryMap.put("kuba","cu");
        countryMap.put("cuba","cu");
        countryMap.put("tajlandia","th");
        countryMap.put("thailand","th");
        countryMap.put("czechy","cz");
        countryMap.put("czechia","cz");
        countryMap.put("turcja","tr");
        countryMap.put("turkey","tr");
        countryMap.put("niemcy","de");
        countryMap.put("germany","de");
        countryMap.put("tajwan","tw");
        countryMap.put("taiwan","tw");
        countryMap.put("ukraina","ua");
        countryMap.put("ukraine","ua");
        countryMap.put("stanyzjednoczone","us");
        countryMap.put("unitedstatesofamerica","us");
        countryMap.put("egipt","eg");
        countryMap.put("egypt","eg");
        countryMap.put("wenezuela","ve");
        countryMap.put("venezuela","ve");
        countryMap.put("francja","fr");
        countryMap.put("france","fr");
        countryMap.put("wielkabrytania","gb");
        countryMap.put("unitedkingdom","gb");
        countryMap.put("grecja","gr");
        countryMap.put("greece","gr");
        countryMap.put("hongkong","hk");
        countryMap.put("hongkong","hk");
        countryMap.put("węgry","hu");
        countryMap.put("hungary","hu");
        countryMap.put("indonezja","id");
        countryMap.put("indonesia","id");
        countryMap.put("irlandia","ie");
        countryMap.put("ireland","ie");
        countryMap.put("izrael","il");
        countryMap.put("israel","il");
        countryMap.put("indie","in");
        countryMap.put("india","in");
        countryMap.put("poludniowaafryka","za");
        countryMap.put("southafrica","za");
        countryMap.put("wlochy","it");
        countryMap.put("italy","it");
        countryMap.put("japonia","jp");
        countryMap.put("japan","jp");
        countryMap.put("koreapoludniowa","kr");
        countryMap.put("koreasouth","kr");
        countryMap.put("litwa","lt");
        countryMap.put("lithuania","lt");
        countryMap.put("lotwa","lv");
        countryMap.put("latvia","lv");
        countryMap.put("maroko","ma");
        countryMap.put("morocco","ma");
        countryMap.put("meksyk","mx");
        countryMap.put("mexico","mx");
        countryMap.put("malezja","my");
        countryMap.put("malaysia","my");
        countryMap.put("nigeria","ng");
        countryMap.put("nigeria","ng");
        countryMap.put("holandia","nl");
        countryMap.put("netherlands","nl");
        countryMap.put("norwegia","no");
        countryMap.put("norway","no");
        countryMap.put("nowazelandia","nz");
        countryMap.put("newzealand","nz");
        countryMap.put("filipiny","ph");
        countryMap.put("philippines","ph");
        countryMap.put("polska","pl");
        countryMap.put("poland","pl");
        return countryMap;
    }
}
